### ISSUE TITLE
Value must not be null

### ISSUE THREAD

**Issue by R-anybbo** [redis-developer/riot#71]
org.springframework.retry.ExhaustedRetryException: Retry exhausted after last attempt in recovery path, but exception is not skippable.; nested exception is java.lang.IllegalArgumentException: Value must not be null
        at org.springframework.batch.core.step.item.FaultTolerantChunkProcessor$5.recover(FaultTolerantChunkProcessor.java:429)
        at org.springframework.retry.support.RetryTemplate.handleRetryExhausted(RetryTemplate.java:539)
        at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:387)
        at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:255)
        at org.springframework.batch.core.step.item.BatchRetryTemplate.execute(BatchRetryTemplate.java:217)
        at org.springframework.batch.core.step.item.FaultTolerantChunkProcessor.write(FaultTolerantChunkProcessor.java:444)
        at org.springframework.batch.core.step.item.SimpleChunkProcessor.process(SimpleChunkProcessor.java:217)
        at org.springframework.batch.core.step.item.ChunkOrientedTasklet.execute(ChunkOrientedTasklet.java:77)
        at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:407)
        at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:331)
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
        at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:273)
        at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:82)
        at org.springframework.batch.repeat.support.TaskExecutorRepeatTemplate$ExecutingRunnable.run(TaskExecutorRepeatTemplate.java:262)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalArgumentException: Value must not be null
        at io.lettuce.core.internal.LettuceAssert.notNull(LettuceAssert.java:71)
        at io.lettuce.core.RedisCommandBuilder.restore(RedisCommandBuilder.java:1918)
        at io.lettuce.core.AbstractRedisAsyncCommands.restore(AbstractRedisAsyncCommands.java:1387)
        at jdk.internal.reflect.GeneratedMethodAccessor24.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.lettuce.core.support.ConnectionWrapping$DelegateCloseToConnectionInvocationHandler.handleInvocation(ConnectionWrapping.java:215)
        at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80)
        at com.sun.proxy.$Proxy34.restore(Unknown Source)
        at org.springframework.batch.item.redis.support.operation.Restore.doExecute(Restore.java:47)
        at org.springframework.batch.item.redis.support.operation.AbstractKeyOperation.execute(AbstractKeyOperation.java:31)
        at org.springframework.batch.item.redis.OperationItemWriter.futures(OperationItemWriter.java:40)
        at org.springframework.batch.item.redis.OperationItemWriter.write(OperationItemWriter.java:34)
        at org.springframework.batch.item.redis.support.AbstractPipelineItemWriter.write(AbstractPipelineItemWriter.java:31)
        at org.springframework.batch.core.step.item.SimpleChunkProcessor.writeItems(SimpleChunkProcessor.java:193)
        at org.springframework.batch.core.step.item.SimpleChunkProcessor.doWrite(SimpleChunkProcessor.java:159)
        at org.springframework.batch.core.step.item.FaultTolerantChunkProcessor$3.doWithRetry(FaultTolerantChunkProcessor.java:348)
        at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:329)
        ... 14 more

**Comment by jruaux** [comment]
Could you share how to reproduce this issue?
